Add Vietnamese translation
donnemartin/system-design-primer pull request #553
Opened 2021-08-04 13:44 UTC by huylenq

Heavily in-progress stuff.

---

## Review the Contributing Guidelines

Before submitting a pull request, verify it meets all requirements in the [Contributing Guidelines](https://github.com/donnemartin/system-design-primer/blob/master/CONTRIBUTING.md).

### Translations

See the [Contributing Guidelines](https://github.com/donnemartin/system-design-primer/blob/master/CONTRIBUTING.md).  Verify you've:

* Tagged the [language maintainer](https://github.com/donnemartin/system-design-primer/blob/master/TRANSLATIONS.md)
* Prefixed the title with a language code
    * Example: "ja: Fix ..."

2021-08-04 14:11 UTC, longqua69 commented
Hi @huylenq 

I'd like to join the Vietnamese translation team. Could you please help me?

Thanks & Best regards,

Anh Tran

2021-08-06 02:15 UTC, Hungsiro506 commented
Lets go.

2021-08-06 02:18 UTC, huylenq commented
@longqua69 , sure thing!
Added you along with @Hungsiro506 as collaborators in the `huylenq/system-design-primer` fork.

2021-08-06 04:35 UTC, longqua69 commented
@huylenq  thanks for inviting me into the translation team. Let's collaborate.

2021-08-06 04:42 UTC, longqua69 approved these changes
As I checked, it's good to merge these changes.

2021-08-06 04:42 UTC, longqua69 commented on README-vi.md
> +- Có những dạng từ khoá chuyên ngành khó mà dịch được một cách thoát nghĩa mà không gượng gạo. Nên bản dịch này sẽ giữ một số từ ngữ ở nguyên bản tiếng Anh, chẳng hạng: "scale", "code" (xem như từ mư
Corrected format only. OK, it's good.

2021-08-06 04:42 UTC, longqua69 approved these changes

2021-08-12 00:21 UTC, longqua69 requested changes

2021-08-12 00:21 UTC, longqua69 commented on README-vi.md
> +* [Các chủ đề thiết kế hệ thống: bắt đầu ở đây](#system-design-topics-start-here)
I think it's better to be:
[Các chủ đề về thiết kế hệ thống: hãy bắt đầu ở đây](#system-design-topics-start-here)

2021-08-12 00:21 UTC, longqua69 commented on README-vi.md
> +* [Availability và tính nhất quán](#availability-vs-consistency)
I think it's better to be:
[Tính sẵn có và tính nhất quán](#availability-vs-consistency)

2021-08-12 00:21 UTC, longqua69 commented on README-vi.md
> +        * [CP - tính nhất quán và partition tolerance](#cp---consistency-and-partition-tolerance)
I think it's better to be:
[CP - tính nhất quán và dung sai phân vùng](#cp---consistency-and-partition-tolerance)

2021-08-12 00:21 UTC, longqua69 commented on README-vi.md
> +        * [AP - availability và partition tolerance](#ap---availability-and-partition-tolerance)
I think it's better to be:
[AP - Tính sẵn có và dung sai phần vùng](#ap---availability-and-partition-tolerance)

2021-08-12 00:21 UTC, longqua69 commented on README-vi.md
> +* [Các mẫu về nhất quán](#consistency-patterns)  # FIXME: bad translation
[Các mẫu thiết kế nhất quán](#consistency-patterns)

2021-08-12 00:21 UTC, longqua69 commented on README-vi.md
> +    * [Nhất quán yếu](#weak-consistency)  # FIXME: bad translation
I think it's better to be:
[Ít Nhất quán](#weak-consistency)

2021-08-22 13:48 UTC, huylenq commented
@longqua69 Great suggestions! Could I ask you to commit and push those over directly to https://github.com/huylenq/system-design-primer/tree/master (you're a collaborator). Would be much more efficient that way, I think.

2021-09-01 15:54 UTC, longqua69 commented
Hi @huylenq 

Thanks for your invitation. I'll contribute to this project. I'm impressed with your work.

2021-12-16 17:00 UTC, qhquanghuy commented on README-vi.md
> +* **Triệt tiêu SSL** - Giải mã các requests đi đến và mã hoá responses từ máy chủ, để các máy chủ không phải thực hiện các thao tác chi chí (tính toán) cao này.
typo: chi chí -> chi phí

2021-12-16 17:27 UTC, qhquanghuy commented on README-vi.md
> +* **Lưu phiên** - Cấp phát cookie và dẫn yêu cầu của máy khách đến đúng bản máy chủ nếu ứng dụng web không phiên  # FIXME: bad translation
What about
Phát hành cookie và điều hướng yêu cầu từ máy khách đến đúng nơi (máy chủ, ứng dụng) mà máy khách đang làm việc nếu các ứng dụng web không theo dõi phiên.

2021-12-17 06:55 UTC, huylenq commented on README-vi.md
> +* **Lưu phiên** - Cấp phát cookie và dẫn yêu cầu của máy khách đến đúng bản máy chủ nếu ứng dụng web không phiên  # FIXME: bad translation
Sounds great, thanks!

2026-07-24 04:33 UTC, closed without merging