de: Add German translation
donnemartin/system-design-primer pull request #831
Opened 2024-01-09 13:44 UTC by jannismilz

## Review the Contributing Guidelines

Before submitting a pull request, verify it meets all requirements in the [Contributing Guidelines](https://github.com/donnemartin/system-design-primer/blob/master/CONTRIBUTING.md).

### Translations

@Allaman (You still maintain)

I'm opening this PR because prior #577 was closed (branch got deleted). I took the existing translation from @MiroAtDavid and adjusted my already suggested changes.

The translation is far from perfect and I didn't read through everything yet (only to around what I suggested last).

I'm looking forward to improvements and reviews from others and I try to improve even more myself but I don't have an abundance of time either 😉

2024-01-10 18:17 UTC, Allaman commented
I'll try but cannot promise anything  🙈

2024-01-10 18:41 UTC, jannismilz commented
> I'll try but cannot promise anything 🙈

@Allaman awesome! I also try my best. Probably gonna look into it again next week during work 😉

2024-06-17 14:18 UTC, jannismilz commented
@Allaman, I would have enough time to maintain the German translation of this project. Do you still have time?

Otherwise, maybe you can transfer the maintainer role to me (via @donnemartin, I guess) so that a German translation can finally be provided.

2024-06-18 18:20 UTC, Allaman commented
Hi @jannismilz,
Unfortunately, I have no time to work on the translation. 

How about me closing https://github.com/donnemartin/system-design-primer/issues/186, and you can open a fresh Issue according to the translation guide.

2024-06-19 05:41 UTC, jannismilz commented
Sure let's do it that way @Allaman 👍

2024-06-19 05:49 UTC, jannismilz commented
#873

2024-06-28 05:35 UTC, atollk commented
Hey. Not trying to hate, but this very much feels like it was just thrown into some automatic translator and had some minor fixes applied. I don't know about the intention of translations in this repository and whether it would be preferred to have a bad translation over no translation at all.

First of all, I think the formal "Siezen" is less appropriate in this document than the informal "Duzen". I've only ever seen the former used in some books, never in online tutorials or documents.

I'll try to write down some review comments but I'd honestly question whether starting from a broken translation is the right approach.

2024-06-28 05:56 UTC, atollk requested changes

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +# The System Design Primer (System Design Fibel)
Systemdesign-Fibel

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +> Vorbereitung für das Systemdesign Interview.
Vorbereitung für ein Bewerbungsgespräch im Systemdesign

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +> Lerne wie man groß skalierte Systeme entwirft.
_Wenn es Siezen sein soll, dann einheitlich:_ Lernen Sie ...

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +### Lerne wie man groß skalierte Systeme entwirft.
Lernen Sie...

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +Während Sie lernen, wie Sie skalierbare Systeme entwerfen, werden Sie zum besseren Ingenieur.
Das Wissen, wie man skalierbare System entwirft, wird Sie zu einem besseren Entwickler machen.

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +Systemdesign ist ein breites Thema. Es ist eine **große Menge an Ressourcen verteilt im ganzen Web** basierend auf dem Thema der Systemdesign Prinzipien.
Systemdeisng ist ein breitgefächertes Thema. Im Internet ist eine **riesige Menge an Ressourcen verteilt**, die das Thema der Systemdesign-Prinzipien behandeln.

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +Dieses Repo ist eine **organisierte Ansammlung** der Ressourcen und wird Ihnen dabei helfen skalierte Systeme zu erlernen.
helfen, zu lernen, wie man skalierbare Systeme baut.

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +[Hilfe zu Beiträgen](#Beitragen) ist erwünscht!
Beiträge zu Inhalten sind gerne gesehen!

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +### Vorbereitung für das Systemdesign Interview.
Systemdesign-Gespräch

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +Neben der Interviews zur Softwareentwicklung ist das Systemdesign bei vielen Technologieunternehmen ein **erforderlicher Bestandteil** des **technischen Interviewprozesses**.
Neben Bewerbungsgesprächen zur Softwareentwicklung ist Systemdesign bei vielen...

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +Die Bereitgestellten [Anki flashcard decks](https://apps.ankiweb.net/) verwenden "spaced repetition" um sich wichtige Systemdesign Konzepte einzuprägen.
Die bereitgestellten Anki flashcard decks verwenden Widerholung mit zeitlichem Abstand, um Ihnen dabei zu helfen, sich wichtige Konzepte des Systemdesigns einzuprägen.

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +* [Systemdesign Deck](https://github.com/donnemartin/system-design-primer/tree/master/resources/flash_cards/System%20Design.apkg)
Deck zum Systemdesign

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +* [Systemdesign Übungen Deck](https://github.com/donnemartin/system-design-primer/tree/master/resources/flash_cards/System%20Design%20Exercises.apkg)
Deck mit Übungen zum Systemdesign

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +* [Objektorientiertes Design Übungen Deck](https://github.com/donnemartin/system-design-primer/tree/master/resources/flash_cards/OO%20Design.apkg)
Deck mit Übungen zu objektorientiertem Design

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +### Programmier Ressourcen: Interaktive Programmierübungen
_"Programmier Ressourcen" entfernen_

2024-06-28 05:56 UTC, atollk commented on README-de.md
> +Von erfahreneren Bewerbern wird im Allgemeinen erwartet, dass sie mehr über das Systemdesign wissen.  Von Architekten oder Projektleitern kann man erwarten, dass sie mehr wissen als einzelne Mitarbei
Projektleitern -> Führungskräften

einzelne Mitarbeiter -> Mitarbeiter mit weniger Verantwortung

2024-07-01 07:23 UTC, jannismilz commented
> Hey. Not trying to hate, but this very much feels like it was just thrown into some automatic translator and had some minor fixes applied. I don't know about the intention of translations in this repository and whether it would be preferred to have a bad translation over no translation at all.
> 
> First of all, I think the formal "Siezen" is less appropriate in this document than the informal "Duzen". I've only ever seen the former used in some books, never in online tutorials or documents.
> 
> I'll try to write down some review comments but I'd honestly question whether starting from a broken translation is the right approach.

First of all, thanks for taking some time to look into this.

The problem with technical translations is if you want to translate as good as possible into the according language or want to keep the context (which have often English words included).

Yes, there once was a discussion about formal vs informal but I can't find it anymore. I would also prefer informal even tho I think out of routine the most things are in formal form...

2026-09-18 15:33 UTC, closed without merging